version: "3.8"

services:
  express:
    image: elsborg/express-app
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 60 # Poll every 60 seconds
      WATCHTOWER_LABEL_ENABLE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
